### ISSUE TITLE
Report Cores, MIPS and SRAM usage

### ISSUE THREAD

**Issue by mbanth** [xmos/fwk_voice#247]
Using the new xformer and the TFL model provided by the Acoustic team, measure and document resource usage, specifically:
- The number of Cores used,
- The maximum MIPS consumed when streaming audio, and
- The amount of SRAM used.

(AV2a)

**Comment by shuchitak** [comment]
Will be addressed as part of https://github.com/xmos/sw_avona/issues/249

**Comment by mbanth** [comment]
We will discuss this issue at the 27 April 2022 Voice Pipeline Performance meeting to gain clarity about its scope and necessity.

**Comment by shuchitak** [comment]
Tracked in https://github.com/xmos/sw_avona/issues/267
