### ISSUE TITLE
Implement control logic

### ISSUE THREAD

**Issue by mbanth** [xmos/fwk_voice#251]
Implement in the Avona repository the control logic specification developed by the Acoustic team. (AV3)

**Comment by shuchitak** [comment]
Based on what I see in https://github.com/xmos/py_ic, [mu_control_system()](https://github.com/xmos/py_ic/blob/develop/py_ic/IC.py#L306) function needs to be implemented to replace the existing [adaption_controller](https://github.com/xmos/sw_avona/blob/main/modules/lib_ic/src/ic_low_level.c#L250) in sw_avona

**Comment by uvvpavel** [comment]
py_ic v2.0.0, with updated pipeline examples, has been implemented with #321.  py_ic v2.1.0, cleanup, documentation update and removing vad from the agc state are captured in #329.

**Comment by uvvpavel** [comment]
Cleanup and documentation updates were merged with #331. py_ic v2.1.0 is now tracked in #332

**Comment by shuchitak** [comment]
py_ic v2.2.0 + py_vnr 0.2.1 Avona port pipeline test results

[py_ic_v2_2_0_results_Avona_prev_arch_xcore.csv](https://github.com/xmos/fwk_voice/files/9148892/py_ic_v2_2_0_results_Avona_prev_arch_xcore.csv)
[py_ic_v2_2_0_results_Avona_alt_arch_xcore.csv](https://github.com/xmos/fwk_voice/files/9148895/py_ic_v2_2_0_results_Avona_alt_arch_xcore.csv)
[develop_results_Avona_prev_arch_xcore.csv](https://github.com/xmos/fwk_voice/files/9148897/develop_results_Avona_prev_arch_xcore.csv)
[develop_results_Avona_alt_arch_xcore.csv](https://github.com/xmos/fwk_voice/files/9148898/develop_results_Avona_alt_arch_xcore.csv)

Prev-arch
![py_ic_v2_2_0_prev_arch](https://user-images.githubusercontent.com/38428600/179959895-e293af4d-0e74-4236-a847-b1485c606944.png)
[py_ic_v2_2_0_prev_arch.csv](https://github.com/xmos/fwk_voice/files/9148902/py_ic_v2_2_0_prev_arch.csv)

Alt-arch
![py_ic_v2_2_0_alt_arch](https://user-images.githubusercontent.com/38428600/179959901-b6c64376-f49c-4fa0-9221-6fe4b84090e7.png)
[py_ic_v2_2_0_alt_arch.csv](https://github.com/xmos/fwk_voice/files/9148903/py_ic_v2_2_0_alt_arch.csv)

**Comment by shuchitak** [comment]
Prev-arch (Avona-develop, lib_ap-master, py_ic_v2.2.0)
![py_ic_v2_2_0_prev_arch](https://user-images.githubusercontent.com/38428600/179962446-129cb94d-d2e4-4888-98c5-7c1639ed138a.png)
[py_ic_v2_2_0_prev_arch.csv](https://github.com/xmos/fwk_voice/files/9148994/py_ic_v2_2_0_prev_arch.csv)

Alt-arch (Avona-develop, lib_ap-master, py_ic_v2.2.0)
![py_ic_v2_2_0_alt_arch](https://user-images.githubusercontent.com/38428600/179962457-cef21906-86ca-4e5d-8a33-70e6f82a3eb0.png)
[py_ic_v2_2_0_alt_arch.csv](https://github.com/xmos/fwk_voice/files/9148995/py_ic_v2_2_0_alt_arch.csv)
