### ISSUE TITLE
Implement new Interference Canceller

### ISSUE THREAD

**Issue by mbanth** [xmos/fwk_voice#252]
Implement in the Avona repository the new Interference Canceller developed by the Acoustic team. (AV3)

**Comment by shuchitak** [comment]
Once [new IC control logic](https://github.com/xmos/sw_avona/issues/251) is implemented, make sure the sw_avona, lib_ic module is compatible with the [python](https://github.com/xmos/py_ic/ ) model. Implement any tests required to test compatibility with the python model.
