### ISSUE TITLE
create equivalent py_avona to replace lib_audio_pipelines/py_aec/py_ic/py_vnr etc

### ISSUE THREAD

**Issue by hughh-xmos** [xmos/fwk_voice#264]
this is a description

**Comment by hughh-xmos** [comment]
some notes from our discussion on this 27/5/2022
1)	Team
Pavel to lead work from the software side and Allan from acoustics.
2)	Project definition
Not just a bare bores copy and paste. noise_suppresor to match XC/C not existing python (which is broken). Should include generic adaptive filter shared between IC/AEC and potentially further refactoring.
3)	Timeline
general idea is to put this after IC/VNR but before any further DSP R&D. py-pipeline can start during development of py_ic/py_vnr although those take priority. Initially py-pipeline can use stable components aec/noise suppressor/etc.

**Comment by uvvpavel** [comment]
The initial project plan discussed by @Allan-xmos and I can be found here:
https://xmosjira.atlassian.net/wiki/spaces/~94391093/pages/3565125645/py+piplines+initial+plan

**Comment by andrewdewhurst** [comment]
2.	This is captured in AV5 as smaller tasks, there will be additional issues to add to AV5 once we’ve decided on the repo structure

Resize to zero and mark done so we keep this history.
