### ISSUE TITLE
New vs. Old IC benchmarks for full pipeline 3610 (eg Amazon noise tests)

### ISSUE THREAD

**Issue by andrewdewhurst** [xmos/fwk_voice#274]

**Comment by shuchitak** [comment]
The best results are on Avona head of develop. The reason for that is increasing IC delay samples from 180 to 600.
New IC has lower kwd scores than Avona head of develop but is better than lib_audio_pipelines. The IC samples delay in lib_audio_pipelines is set to 180 samples though. We don't have lib_audio_pipelines results for IC delay set to 600 but we expect it would show an increased kwd performance as well.

For alt-arch, new IC is in general, better than lib_audio_pipelines but worse than Avona head of develop.

For prev-arch, new IC shows lower performance than lib_audio_pipelines for most of the barge-in streams. Copying results where new IC is worse than lib_audio_pipelines for prev-arch.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/shuchitak/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/shuchitak/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Input | develop_results_Avona_prev_arch_xcore_Amazon_WR_250k.en-US | new_ic_results_Avona_prev_arch_xcore_Amazon_WR_250k.en-US | results_pipelines_prev_arch_xcore_Amazon_WR_250k.en-US
-- | -- | -- | --
InHouse_XVF3510v080_v1.2_20190423_Loc1_Clean_XMOS_DUT1_70dB_Take1.wav | 99 | 98 | 100 |   | -2
InHouse_XVF3510v080_v1.2_20190423_Loc1_Clean_XMOS_DUT1_80dB_Take1.wav | 98 | 92 | 95 |   | -3
InHouse_XVF3510v080_v1.2_20190423_Loc1_Clean_XMOS_DUT1_90dB_Take1.wav | 5 | 3 | 10 |   | -7
InHouse_XVF3510v080_v1.2_20190423_Loc1_Noise1_65dB_XMOS_DUT1_80dB_Take1.wav | 92 | 83 | 92 |   | -9
InHouse_XVF3510v080_v1.2_20190423_Loc2_Clean_XMOS_DUT1_80dB_Take1.wav | 92 | 87 | 92 |   | -5
InHouse_XVF3510v080_v1.2_20190423_Loc2_Clean_XMOS_DUT1_90dB_Take1.wav | 5 | 7 | 11 |   | -4
InHouse_XVF3510v080_v1.2_20190423_Loc2_Noise1_65dB__Take1.wav | 98 | 95 | 97 |   | -2
InHouse_XVF3510v080_v1.2_20190423_Loc2_Noise1_70dB__Take1.wav | 96 | 94 | 95 |   | -1
InHouse_XVF3510v080_v1.2_20190423_Loc3_Clean_XMOS_DUT1_70dB_Take1.wav | 100 | 99 | 100 |   | -1
InHouse_XVF3510v080_v1.2_20190423_Loc3_Clean_XMOS_DUT1_80dB_Take1.wav | 96 | 89 | 95 |   | -6
InHouse_XVF3510v080_v1.2_20190423_Loc3_Clean_XMOS_DUT1_90dB_Take1.wav | 6 | 9 | 14 |   | -5
InHouse_XVF3510v080_v1.2_20190423_Loc3_Noise1_70dB__Take1.wav | 99 | 98 | 99 |   | -1



</body>

</html>

**Comment by shuchitak** [comment]
The lower performance for barge-in needs investigation. We need to check the VNR performance with AEC output as it's input.
