### ISSUE TITLE
Workaround for wrong headroom reported in FFT output issue

### ISSUE THREAD

**Issue by shuchitak** [xmos/fwk_voice#288]
Add workaround to fix FFT output headroom in AEC and NS modules (similar to [this](https://github.com/xmos/sw_avona/blob/develop/modules/lib_vnr/src/features/vnr_features_priv.c#L22)) till https://github.com/xmos/lib_xs3_math/issues/96 is fixed.

**Comment by shuchitak** [comment]
https://github.com/xmos/sw_avona/pull/289

**Comment by mbanth** [comment]
@shuchitak, thanks for filling in the Story Points field.  Please upfdate the Status field to reflect the correct status.
