### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by mbanth** [xmos/fwk_voice#309]
The continued use of sw_avona is causing all sorts of confusion.  Some people are drawing incorrect inferences between sln_avona and sw_avona.  Many people do not understand the relationship between Avona as a business/marketing concept and sw_avona as a suite of audio DSP components.  We need to rename this repo to minimize the confusion.

The most recent naming convention for repos submoduled into the xcore_sdk uses fwk_* as a pattern, e.g., fwk_core, fwk_io.  I propose that we rename this repo to fwk_voice or fwk_voice_dsp.

**Comment by shuchitak** [comment]
I've opened PR https://github.com/xmos/sw_avona/pull/322 for renaming Avona in python and CMake files.

Once this is merged, I'll open 2 separate PRs for
- Renaming the sw_avona repo and fixing repo path in scripts.
- Update documentation.
