### ISSUE TITLE
Create shared adaptive filter in C

### ISSUE THREAD

**Issue by uvvpavel** [xmos/fwk_voice#356]
Move low-level AEC functions into a new static library. Make some small design changes for the ease of future development. Move the AEC unit test as well? Do not add new tests

**Comment by shuchitak** [comment]
> Move the AEC unit test as well?

Since the AEC unit tests test the AEC API functions and not the lower level APIs I don't recommend we move them out of AEC testing.

**Comment by mbanth** [comment]
A review by @andrewdewhurst and myself has concluded that we will not work on this issue.
