### ISSUE TITLE
Pipeline test fails in the short Jenkins run

### ISSUE THREAD

**Issue by uvvpavel** [xmos/fwk_voice#366]

**Comment by uvvpavel** [comment]
Being tested in #359 an a test branch in origin

**Comment by uvvpavel** [comment]
I could not locate the reason behind the failures I've seen. The temporary way to fix this is to move pipeline tests to run before the examples. This does seem to work from the two successful runs I've seen.

**Comment by shuchitak** [comment]
Fixed in https://github.com/xmos/fwk_voice/pull/368
