### ISSUE TITLE
Port py_ic v2.3.0 to fwk_voice

### ISSUE THREAD

**Issue by shuchitak** [xmos/fwk_voice#369]
- [x] Port to fwk_voice and ensure tests pass
- [x] Benchmark keywords test performance against lib_audio_pipelines

**Comment by shuchitak** [comment]
Avona full pipeline keyword test results compared with lib_audio_pipelines

Alt-arch

**Comment by shuchitak** [comment]
Avona full pipeline keyword test results compared with lib_audio_pipelines

Prev-arch

![Prev_arch_DUT_Audio___XMOS_DUT1_Env_Audio___Clean](https://user-images.githubusercontent.com/38428600/185142986-4d7e12d2-8b5c-49e9-9545-63a8448a332a.png)
![Prev_arch_DUT_Audio___XMOS_DUT1_Env_Audio___Noise1](https://user-images.githubusercontent.com/38428600/185143012-0e851aa3-c4ad-4dd3-a9a3-7f5fa14ed667.png)
![Prev_arch_Env_Audio___Noise1](https://user-images.githubusercontent.com/38428600/185143029-f049db5d-dea2-42e4-9f94-437d89ab7e6a.png)
![Prev_arch_Env_Audio___Noise2](https://user-images.githubusercontent.com/38428600/185143042-4fce9610-0a78-44ef-8de0-22312597aee4.png)

**Comment by shuchitak** [comment]
Avona pipeline results compared with the python pipeline in prev_arch mode with Initial delay estimation using the ADEC disabled.

![python_DUT_Audio___XMOS_DUT1_Env_Audio___Clean](https://user-images.githubusercontent.com/38428600/185143269-b58064f8-ccf5-41da-bbf5-bb2b9c7bfd76.png)
![python_DUT_Audio___XMOS_DUT1_Env_Audio___Noise1](https://user-images.githubusercontent.com/38428600/185143289-e795cdbf-a5c5-4a74-8c39-a6babd2bd313.png)
![python_Env_Audio___Noise1](https://user-images.githubusercontent.com/38428600/185143301-00effbd0-53b4-41d3-8c3e-dc42b27c1e87.png)
![python_Env_Audio___Noise2](https://user-images.githubusercontent.com/38428600/185143320-cd245932-ece3-468a-aea3-1705a24f50c3.png)

**Comment by mbanth** [comment]
@uvvpavel or @shuchitak, what additional work needs to occur to resolve this issue?
