### ISSUE TITLE
Integrate new version of Tensorflow Lite Micro

### ISSUE THREAD

**Issue by mbanth** [xmos/fwk_voice#378]
We have a improved version of Tensorflow Lite Micro.  The developer wants to make it available for use in fwk_voice and specifically the Voice-Noise Ratio component.  This issue exists to identify and complete any necessary work to integrate this new version of TFLM.

**Comment by uvvpavel** [comment]
- [ ] Build lib_vnr as a static library
- [ ] Use new tflite_mirco_compiler and change vnr calls
- [ ] Move calc_vnr_pred into IC
- [ ] xcore build
- [ ] x86 build
- [ ] All tests passing
- [ ] Think about SDK integration

**Comment by uvvpavel** [comment]
One of the python cffi tests exits with the segmentation error which is usually related to using memory outside of the allocated stack or stack running out of memory. This line appears to break the test.
https://github.com/uvvpavel/sw_avona-1/blob/latest_tflite_micro/modules/lib_vnr/src/inference/model/outFile.cpp#L35
Making the kTensorArenaSize larger makes the test pass. This issue will be parked till @panickal-xmos is back from holiday.
