### ISSUE TITLE
broken docs since v2 of doc_builder

### ISSUE THREAD

**Issue by BrennanGit** [xmos/fwk_voice#387]
example:
https://github.com/xmos/fwk_voice/actions/runs/3327995023/jobs/5503721918#step:4:668

Issue comes up between sphinx v4.4 and v4.5: https://github.com/sphinx-doc/sphinx/compare/v4.4.0..v4.5.0
Confirmed that pinning every other dependency and only changing the sphinx version repros the effect.

Issue goes away if removing "content-only" from files like "modules/lib_aec/doc/src/reference/header_files.rst"
Which does have an effect on the rendering. It *should* work but if it doesn't, it's not the largest price to pay.

### with sphinx 4.4 and content-only

![Image](https://user-images.githubusercontent.com/15315756/198672259-688a66d6-313d-4405-a9e1-418ed00052b6.png)
![Image](https://user-images.githubusercontent.com/15315756/198672325-aee84567-6ad8-4296-88d3-d6a82ee7a742.png)

### with sphinx 5.2 without content-only

![Image](https://user-images.githubusercontent.com/15315756/198672480-e5b379d2-decd-490c-a0ac-e4b1fd83586c.png)
![Image](https://user-images.githubusercontent.com/15315756/198672536-3971f025-ddcb-466b-8269-1502663e8c1d.png)

**Comment by BrennanGit** [comment]
This issue will likely be solved in a later release of sphinx but we have no guarantees when.
Our options then are:
- downgrade to sphinx 4.4 in doc_builder and rerelease it
- remove the "content-only" doxygen option and accept the slightly more cluttered appearance

**Comment by andrewdewhurst** [comment]
I propose we **comment out** the content-only directive for now.  At least this way, it would be simply to un-comment it at somw later date if this functionality is fixed.

**Comment by BrennanGit** [comment]
Ok the artifacts in the latest develop build look ok to me. They all have the extra `page` lines from the removed `content-only` but we have pdfs and html that looks the same.
