### ISSUE TITLE
Documentation formatting review

### ISSUE THREAD

**Issue by mbanth** [xmos/fwk_voice#391]
Review and, if necessary, update the formatting of the User Guide and Getting Started Guide to make them suitable for release.  The work covers both the HTML and PDF versions of the documents.

[Documents as generated on 2023-02-16](https://github.com/xmos/fwk_voice/actions/runs/4193714944) (the documents may become unavailable; GitHub keeps them for a limited period of time).

**Comment by mbanth** [comment]
@lucianomartin, I have placed this issue on both the Bristol Software and the SDK Team project boards.  I have taken this action so that both @keithm-xmos and myself have visibility to it.  Please keep both sets of Status up to date.  Also, please provide a Story Point value for the work.  Thanks.

**Comment by lucianomartin** [comment]
@mbanth, let me know if more changes are necessary to close this issue.

**Comment by mbanth** [comment]
> @mbanth, let me know if more changes are necessary to close this issue.

I have sent the email below to @jacobh-xmos and @keithm-xmos, seeking information:

> Luciano has reviewed the existing XCORE-VOICE documentation and provided updates.  Without having some documentation requirements, I cannot determine whether it is suitable for a 1.0 release or not.  It appears to consist, largely, of information about each function’s interface and a bit of guidance on how to build and run the examples.  The information available is extensive, however neither Luciano nor I found guidance on how a customer might use the various components to construct a voice pipeline.

> Can either of you point me toward a requirements document for XCORE-VOICE?  In lieu of one, who has oversight responsibility to determine if the documentation is good enough?
