### ISSUE TITLE
Getting Started guide updates

### ISSUE THREAD

**Issue by mbanth** [xmos/fwk_voice#393]
A review of the Getting Started guide on 2023-02-17 revealed two concerns:

1. Section 2 states that the procedure for building only works for MacOS and Linux, but it includes instructions for Windows as well.
2. The PDF shows both the MacOS/Linux instructions and the Windows instructions without indicating which instruction works for which operating system.  In the HTML, the different instructions appear as OS-selectable alternatives.

@keithm-xmos has stated that the reference design supports Windows as well as MacOS/Linux.  He has also said that he will correct the content of the Getting Started guide.  Consequently, this issue only covers fixing the format of the text so that the PDF correctly indicates which operating system applies to the different instructions.  Finally, he has said that this Getting started guide will not be a part of the XCORE-VOICE release coming up soon.  Hence, I have dropped its priority to 'Could'.

**Comment by mbanth** [comment]
@lucianomartin, please provide a Story Point value for this issue.  Thanks.

**Comment by lucianomartin** [comment]
I spoke with @BrennanGit and he confirmed that tabs are not supported for the PDF generation in Sphynx, we could try to achieve that using some raw latex headings, but I think we find a simpler solution by using list, as in the example below.

![Screenshot from 2023-02-17 15-54-33](https://user-images.githubusercontent.com/16596810/219702710-963e755d-5783-44ae-9a10-67f3145ed2a3.png)

@keithm-xmos and @mbanth, would the solution above work for you?

**Comment by keithm-xmos** [comment]
Yes.  We also observed that the tab directive is not supported in PDFs.

**Comment by mbanth** [comment]
I'm happy to use a list instead of tabs.

**Comment by lucianomartin** [comment]
@mbanth, let me know if more changes are necessary to close this issue.

**Comment by mbanth** [comment]
> @mbanth, let me know if more changes are necessary to close this issue.

I know of no further work needed to close this issue.
